[workspace]
resolver = "2"
members = [
    "crates/trellis",
    "crates/trellis-core",
    "crates/trellis-parse",
    "crates/trellis-rpc",
    "crates/trellis-macros",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"
repository = "https://github.com/rhizome-lab/trellis"
